### ISSUE TITLE
关于单元测试

### ISSUE THREAD

**Issue by Oopswc** [lzjun567/zhihu-api#22]
单元测试里面实现的那些类，**测试入口**在哪里，不需要写类的**实例**吗？
 一点疑问：测试文件夹下的py文件名和modules下的**一模一样**，这个有什么说法吗？
@lzjun567

**Comment by lzjun567** [comment]
1. 你说的类的实例是指哪？可以用指出是哪处的代码吗？
2. 保持一致是希望可以从单元测试里面直接看出对应到哪个model

**Comment by Oopswc** [comment]
我的意思是,在测试类里面不需要定义一个类似以下的语句吗?
if __name__ =='__main__':
    unittest.main()
然后执行该测试类文件的时候,会自动调用该方法.

**Comment by lzjun567** [comment]
python -m unittest -v test_module

**Comment by Oopswc** [comment]
涨姿势了，谢谢
