### ISSUE TITLE
调用发送消息（send_message）API时出错

### ISSUE THREAD

**Issue by kylin60** [lzjun567/zhihu-api#34]
我在调用发送消息（send_message）API时，出现了错误。我认真看了看报错，没找出根源。

但我发现某处代码好像有问题：
      `在Model类中，_user_id方法中，有一行代码：
       “profile = self.user(user_slug=user_slug)"
       
       类中并没有user这一方法呢。

**Comment by lzjun567** [comment]
在父类中有这个方法
